Darrieta
dlab-team/c7-frontend pull request #10
Opened 2023-02-04 21:14 UTC by damian-arrieta

Add navbar sections, logo and styles

2023-02-05 01:40 UTC, gonzafg2 requested changes
Damian, React Router DOM no tiene que ver con agregar el componente del NavBar, por favor quítalo hasta que lo usemos, no deberías incluir en este PR el package.json ni el package-lock.json

Para el CSS me gustaría que se aplicara SASS y BEM, está en otra HU la inclusión de SASS, por lo que cuando esté lista esa HU (Aprobada y mergeada con la rama developer) debes hacerle pull a la rama developer para traerla

2023-02-05 19:53 UTC, damian-arrieta commented
Tome la tarea de agregar SASS al proyecto por que vi que nadie la habia tomado, una vez realizada esta tarea corregi lo que me marcaste. Por lo que en este push se resolvio la tarea c7-40 y c7-29

2023-02-06 19:54 UTC, Lizander90 commented
hermano creo qe el pull req deberia hacerlo a develop no a main!!!

2023-02-07 23:40 UTC, gonzafg2 requested changes
Damian, los archivos package.json y package-lock.json no van en el .gitignore

2023-02-08 13:30 UTC, closed without merging