Lizander c7 151-- EL HOT FIX  LOS MODALES
dlab-team/c7-frontend pull request #111
Opened 2023-04-28 20:49 UTC by Lizander90

![2023-04-25_01-29_1](https://user-images.githubusercontent.com/106877353/235251691-530b6840-663e-43fe-af7a-2899964ba058.jpeg)
![2023-04-25_01-29](https://user-images.githubusercontent.com/106877353/235251714-53354188-2bf1-4981-9ded-50ea169ca2d4.jpeg)

2023-04-28 22:30 UTC, federico-puppo approved these changes

2023-04-29 23:02 UTC, damian-arrieta requested changes
No cargar el archivo package-lock.json

2023-05-01 15:30 UTC, Lizander90 commented
me explicas mejor xD?? que quite el package-lock del PR ??

2023-05-02 23:15 UTC, gonzafg2 approved these changes

2023-05-02 23:39 UTC, merged