titulo del banner, estilos de texto generales y estilos de botones
dlab-team/c7-frontend pull request #12
Opened 2023-02-06 19:51 UTC by Lizander90

Cree el componente <NewContrat_article /> que renderiza el titulo, texto y boton que esta en el banner. (responsivo)
![Componente](https://user-images.githubusercontent.com/106877353/217069598-db81df9f-8f9d-48a0-8537-4b2389644edc.jpg)

**Implemente styles/global_styles.scss:
contiene las fuentes globales para lograr hergonomia en el sitio, todo tendra el mismo tamaño segun la maqueta de figma.

pd: seria optimo tener un scss global donde esten los estandares de maquetando del sitio, agrege tambien el formato de los botones.

2023-02-13 22:18 UTC, zeed3v approved these changes
OK!

2023-02-23 22:53 UTC, gonzafg2 requested changes
Por favor resolver conflictos

2023-02-23 23:20 UTC, gonzafg2 commented
Por favor resolver conflictos

2023-02-25 20:07 UTC, Lizander90 commented
gonza ya todos los conflictos estan solucionados y las cosas que tenia mal arregladas

2023-02-27 16:05 UTC, gonzafg2 requested changes
Camilo, todo ok, por favor quita el package-lock del PR y estamos

2023-02-27 16:27 UTC, Lizander90 commented
ya agregue el ignore deja hacerlo con todos los demas, mis PR ya stan todos bien si los puedes aprobar en orden mejor xD

2023-02-27 22:45 UTC, gonzafg2 approved these changes
ok

2023-02-27 22:45 UTC, merged