Lizander c7 52
dlab-team/c7-frontend pull request #23
Opened 2023-02-16 14:04 UTC by Lizander90

Depende del PR de la estructura del proyecto no aprbar aun para testear errores y tal

2023-02-16 23:26 UTC, zeed3v approved these changes
OK!

2023-02-23 23:19 UTC, gonzafg2 commented
@Lizander90 por favor resolver conflictos

2023-02-26 12:39 UTC, Lizander90 commented
conflictos arreglados, hay algunos conflictos que realmente no se que pasa con ellos, las lineas de codigo estan iguales xD.
Componente funcionando 100%

2023-02-27 23:22 UTC, gonzafg2 requested changes
por favor quitar el .gitignore con el package-lock

2023-02-28 20:28 UTC, Lizander90 commented
Listo sin conflictos,

2023-02-28 21:35 UTC, gonzafg2 approved these changes
Bien

2023-02-28 21:35 UTC, merged