Lizander c7 59
dlab-team/c7-frontend pull request #26
Opened 2023-02-18 17:11 UTC by Lizander90

commit a la rama develop, el PR anterior lo hice mal a la rama main.

![vista loginjpg](https://user-images.githubusercontent.com/106877353/219878797-56de4cdc-38c8-428e-8a5a-7dce74e38433.jpg)

2023-02-20 14:12 UTC, zeed3v approved these changes
OK!

2023-02-23 23:17 UTC, gonzafg2 requested changes
Por favor revisar la estructura de clases con BEM en el componente Login y quitar el !important

2023-02-28 13:33 UTC, Lizander90 commented
listo para merge, vista login

2023-02-28 21:42 UTC, damian-arrieta reviewed
Tiene conflictos

2023-02-28 21:52 UTC, zeed3v commented
> Tiene conflictos

Resuelto

2023-02-28 21:55 UTC, gonzafg2 requested changes
Quitar lo indicado

2023-02-28 21:55 UTC, gonzafg2 commented on src/styles/App.scss
> +<<<<<<< HEAD
Esto hay que quitarlo, cuando se hacen resoluciones manuales de conflictos estos HEAD y hash se deben quitar

2023-02-28 22:01 UTC, zeed3v commented on src/styles/App.scss
> +<<<<<<< HEAD
Ok, gracias, voy a revisar nuevamente

2023-02-28 22:04 UTC, gonzafg2 requested changes
Revisar App.scss

2023-02-28 22:04 UTC, gonzafg2 commented on src/styles/App.scss
> +
Quitar linea agregada, no aporta nada en el PR

2023-02-28 22:55 UTC, federico-puppo approved these changes
ok!

2023-03-01 15:14 UTC, Lizander90 reviewed
App.scss estaba igual, lo solucione copiando el mismo archido scss de develop.

2023-03-01 15:14 UTC, Lizander90 commented on src/views/home/index.js
> -            <SectionSinJrsNoHaySrs/>
este es un conflicto?

2023-03-01 15:20 UTC, damian-arrieta reviewed
Cambiale el nombre a los archivos adentro de la carpeta login para que queden como los demas componentes del proyecto. Login.js y Login.scss

2023-03-01 15:25 UTC, damian-arrieta approved these changes
Esta OK!

2023-03-01 15:27 UTC, federico-puppo approved these changes
Ok

2023-03-01 15:50 UTC, gonzafg2 approved these changes
Bien

2023-03-01 15:51 UTC, merged