C7-53 - Added form landing page component with validations
dlab-team/c7-frontend pull request #29
Opened 2023-02-20 20:51 UTC by federico-puppo

C7-53 - Added form component with validations.

![image](https://user-images.githubusercontent.com/77648181/220196623-a9e24f2f-412b-41dc-85ff-384eb98a2740.png)

2023-02-23 23:07 UTC, gonzafg2 commented on src/components/contactForm/ContactForm.js
> +        //console.log(form);
Quitar console.log por favor

2023-02-23 23:07 UTC, gonzafg2 commented on src/components/contactForm/ContactForm.js
> +        alert(JSON.stringify(form));
Quitar alert ( es peor al console.log)

2023-02-23 23:10 UTC, gonzafg2 commented on src/components/contactForm/contactForm.scss
> +    background-color: $light-blue !important;
Por favor revisar el uso de !important, no debería utilizarlo

2023-02-23 23:12 UTC, gonzafg2 requested changes
Por favor revisar comentarios

2023-02-27 20:17 UTC, zeed3v approved these changes
Conflictos resueltos, se dejan los elementos actualizados para que pasen a Develop

2023-02-28 22:56 UTC, Lizander90 approved these changes
okok

2023-03-01 15:28 UTC, Lizander90 commented on src/index.js
> -import '../node_modules/bootstrap/dist/css/bootstrap.min.css';
fede staba revisando tu PR asi x arribita, y ya en config scss importamos los estilos d bootstrap

2023-03-01 21:14 UTC, federico-puppo commented on src/index.js
> -import '../node_modules/bootstrap/dist/css/bootstrap.min.css';
ahi lo corregi, gracias!

2023-03-02 00:55 UTC, gonzafg2 approved these changes
Bien

2023-03-02 00:55 UTC, merged