Lizander-c7-60
dlab-team/c7-frontend pull request #30
Opened 2023-02-21 19:47 UTC by Lizander90

Vista de nuevo developer, responsivo y con todos los estilos. Adicionalmente le incorpore un placeHolder.

![REGISTRO](https://user-images.githubusercontent.com/106877353/220443637-80435330-1648-4eea-8045-492fa5f46f70.jpg)

2023-02-21 22:06 UTC, federico-puppo approved these changes

2023-02-23 22:59 UTC, gonzafg2 commented on src/views/registrar/index.js
> +        <div className='modal--login--container'>
Por favor utilizar BEM correctamente:
Este nombre de clase (modal--login--container) no significa nada
El bloque quebería ser modal-login-container

2023-02-23 23:00 UTC, gonzafg2 commented on src/views/registrar/index.js
> +            <div className='modal--login'>
Esta clase es un elemento no un modificador: modal--login

Debería ser así: modal-login-container__login

2023-02-23 23:00 UTC, gonzafg2 commented on src/views/registrar/index.js
> +                <div className='subject--text--title'> Regístrate </div>
Esto es un elemento de BEM
Debería ser así: modal-login-container__text-title

2023-02-23 23:01 UTC, gonzafg2 commented on src/views/registrar/index.js
> +                <div className='modal--text'>
Esto es un elemento de BEM no un modificador:
Debería ser así: modal-login-container__text

2023-02-23 23:01 UTC, gonzafg2 commented on src/views/registrar/index.js
> +                <div className='modal--container--buttons'>
Idem arriba!

2023-02-23 23:02 UTC, gonzafg2 commented on src/views/registrar/styles.scss
> +.modal--login--container {
La clase de bloque debería ser la clase padre y dentro deberían estar las clases elemento de BEM anidadas con el &

Ej:

.modal-login-container{
  &__text {}
  &__text-title {}
}

2023-02-23 23:03 UTC, gonzafg2 commented on src/views/registrar/styles.scss
> +  background-color: rgba(226, 242, 254, 1) !important;
No utilizar !important por favor

2023-02-23 23:03 UTC, gonzafg2 commented on src/views/registrar/styles.scss
> +    opacity: 20% !important;
No utilizar !important por favor

2023-02-23 23:04 UTC, gonzafg2 commented on src/App.js
> +    <Ui_register />
Por favor utilizar utilizar PascalCase para el nombre de los componentes como etiqueta

2023-02-23 23:04 UTC, gonzafg2 requested changes
Por favor revisar los comentarios

2023-02-28 13:49 UTC, Lizander90 commented
rama lista para merge, sin conflictos y errores corregidos.
Ui_home ---> UiHome
packpage-lock ---> quitado de git.ignore

2023-02-28 21:57 UTC, zeed3v approved these changes
OK

2023-03-01 17:44 UTC, Lizander90 commented
Ya con este PR todo esta bien acomodado, arreglado conflictos de scss, y de cambio de nombres, la landing esta ya conformada solo falta el formulario

2023-03-01 17:52 UTC, federico-puppo approved these changes

2023-03-01 18:01 UTC, gonzafg2 requested changes
Revisar archivo sin cambios significativos y renombrar componente según lo que menciono en el detalle por favor.

2023-03-01 18:01 UTC, gonzafg2 commented on src/views/home/home.js
> +            <Section />
Por favor que el nombre del componente sea más descriptivo, Section no dice mucho

2023-03-01 18:01 UTC, gonzafg2 commented on .gitignore
> +
Cuidado en subir archivos con cambios solamente en espacio o saltos de líneas, quitar este archivo del PR

2023-03-01 18:37 UTC, Lizander90 commented
corregido linea demas y componente con nombre mas desscriptivo

2023-03-01 21:41 UTC, gonzafg2 approved these changes
ok

2023-03-01 21:41 UTC, merged